In [12]:
import pandas as pd

In [13]:
ls

 El volumen de la unidad C es Windows
 El n£mero de serie del volumen es: EAA5-768A

 Directorio de C:\Users\Francisco\Documents\Programaci¢n\Projects_Pythom\Python-basicos-02

10/03/2022  18:05    <DIR>          .
10/03/2022  18:05    <DIR>          ..
10/03/2022  18:00    <DIR>          .ipynb_checkpoints
10/03/2022  17:37    <DIR>          data
10/03/2022  17:53    <DIR>          data2
10/03/2022  17:38            15.654 Ejemplo-Pandas-01.ipynb
10/03/2022  18:05            22.609 Ejemplo-Pandas-01-V1.2.ipynb
10/03/2022  17:15             2.034 Ejemplo-Pandas-02.ipynb
10/03/2022  17:15    <DIR>          images
10/03/2022  17:15               721 README.md
               4 archivos         41.018 bytes
               6 dirs  70.947.454.976 bytes libres

In [14]:
ls .\data2

 El volumen de la unidad C es Windows
 El n£mero de serie del volumen es: EAA5-768A

 Directorio de C:\Users\Francisco\Documents\Programaci¢n\Projects_Pythom\Python-basicos-02\data2

10/03/2022  17:53    <DIR>          .
10/03/2022  17:53    <DIR>          ..
10/03/2022  17:15                88 .~lock.data-mundial-2018-01.csv#
10/03/2022  18:05            38.050 data-mundial-2018-01.csv
10/03/2022  17:15            47.010 data-mundial-2018-02.csv
               3 archivos         85.148 bytes
               2 dirs  70.947.454.976 bytes libres

In [15]:
data1 = pd.read_csv("data2/data-mundial-2018-01.csv")
data2 = pd.read_csv("data2/data-mundial-2018-02.csv")

In [16]:
data1.keys()

Index(['ID', 'Numero', 'FIFADisplayName', 'Country', 'LastName', 'FirstName'], dtype='object')

In [17]:
data1.shape

(636, 6)

In [18]:
data2.keys()

Index(['ID', 'ShirtName', 'DOB', 'POS', 'Club', 'Height', 'Caps', 'Goals'], dtype='object')

In [19]:
data2.shape

(736, 8)

In [20]:
data1.head()

   ID  Numero     FIFADisplayName    Country    LastName          FirstName
0   1       1       Nahuel GUZMAN  Argentina      GUZMÁN     Nahuel Ignacio
1   2       2     Gabriel MERCADO  Argentina     MERCADO       Gabriel Ivan
2   3       3  Nicolas TAGLIAFICO  Argentina  TAGLIAFICO  Nicolás Alejandro
3   4       4    Cristian ANSALDI  Argentina     ANSALDI    Cristian Daniel
4   5       5        Lucas BIGLIA  Argentina      BIGLIA      Lucas Rodrigo

In [21]:
data2.head()

   ID   ShirtName         DOB POS              Club  Height  Caps  Goals
0   1      GUZMÁN  10.02.1986  GK      Tigres (MEX)     192     6      0
1   2     MERCADO  18.03.1987  DF  Sevilla FC (ESP)     181    20      3
2   3  TAGLIAFICO  31.08.1992  DF        Ajax (NED)     169     4      0
3   4     ANSALDI  20.09.1986  DF      Torino (ITA)     181     5      1
4   5      BIGLIA  30.01.1986  MF    AC Milan (ITA)     175    57      1

In [31]:
tablaFinal = pd.merge(data1, data2, on="ID")

In [32]:
tablaFinal.head()

,ID,Numero,FIFADisplayName,Country,LastName,FirstName,ShirtName,DOB,POS,Club,Height,Caps,Goals
0,1,1,Nahuel GUZMAN,Argentina,GUZMÁN,Nahuel Ignacio,GUZMÁN,10.02.1986,GK,Tigres (MEX),192,6,0
1,2,2,Gabriel MERCADO,Argentina,MERCADO,Gabriel Ivan,MERCADO,18.03.1987,DF,Sevilla FC (ESP),181,20,3
2,3,3,Nicolas TAGLIAFICO,Argentina,TAGLIAFICO,Nicolás Alejandro,TAGLIAFICO,31.08.1992,DF,Ajax (NED),169,4,0
3,4,4,Cristian ANSALDI,Argentina,ANSALDI,Cristian Daniel,ANSALDI,20.09.1986,DF,Torino (ITA),181,5,1
4,5,5,Lucas BIGLIA,Argentina,BIGLIA,Lucas Rodrigo,BIGLIA,30.01.1986,MF,AC Milan (ITA),175,57,1

In [33]:
tablaFinal.shape

(636, 13)

In [36]:
data1.merge(data2, how='right', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)

,ID,Numero,FIFADisplayName,Country,LastName,FirstName,ShirtName,DOB,POS,Club,Height,Caps,Goals
0,1,1.0,Nahuel GUZMAN,Argentina,GUZMÁN,Nahuel Ignacio,GUZMÁN,10.02.1986,GK,Tigres (MEX),192,6,0
1,2,2.0,Gabriel MERCADO,Argentina,MERCADO,Gabriel Ivan,MERCADO,18.03.1987,DF,Sevilla FC (ESP),181,20,3
2,3,3.0,Nicolas TAGLIAFICO,Argentina,TAGLIAFICO,Nicolás Alejandro,TAGLIAFICO,31.08.1992,DF,Ajax (NED),169,4,0
3,4,4.0,Cristian ANSALDI,Argentina,ANSALDI,Cristian Daniel,ANSALDI,20.09.1986,DF,Torino (ITA),181,5,1
4,5,5.0,Lucas BIGLIA,Argentina,BIGLIA,Lucas Rodrigo,BIGLIA,30.01.1986,MF,AC Milan (ITA),175,57,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,732,NaN,NaN,NaN,NaN,NaN,S. COATES,07.10.1990,DF,Sporting CP (POR),196,30,1
732,733,NaN,NaN,NaN,NaN,NaN,J. URRETAVISCAYA,19.03.1990,FW,Monterrey (MEX),172,4,0
733,734,NaN,NaN,NaN,NaN,NaN,E. CAVANI,14.02.1987,FW,Paris Saint-Germain (FRA),188,101,42
734,735,NaN,NaN,NaN,NaN,NaN,M. CACERES,07.04.1987,DF,Lazio (ITA),178,76,4
735,736,NaN,NaN,NaN,NaN,NaN,M. SILVA,25.03.1983,GK,Clube de Regatas Vasco da Gama(BRA),187,11,0

In [21]:
tablaFinal.to_csv("data/data-mundial.csv")